config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  devise_for :users
  root to: "home#index"
  resources :articles do 
    resources :votes, only: %i[create destroy]

  end
  resources :categories, only: %i[index new show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  scope :by_most_recent, -> { order(created_at: :desc) }
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :relationships, dependent: :destroy
  has_many :categories, through: :relationships
  has_many :votes, dependent: :destroy
  has_attached_file :image,
                    storage: :cloudinary,
                    path: ':class/:id/:style/:filename'

  validates :title, presence: true, length: { in: 3..20 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png']
  validates_attachment_presence :image

  def category_list
    categories.collect(&:name).join(', ')
  end

  def category_list=(categories_string)
    category_names = categories_string.split(',').collect { |s| s.strip.downcase }.uniq
    new_or_found_categories = category_names.collect { |name| Category.find_or_create_by(name: name) }
    self.categories = new_or_found_categories
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :relationships, dependent: :destroy
  has_many :articles, through: :relationships
  validates :name, presence: true, length: { in: 3..20 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, foreign_key: 'author_id', dependent: :destroy
  validates :name, presence: true, length: { in: 3..20 }
  has_many :votes, foreign_key: 'author_id', dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article
  belongs_to :author, class_name: 'User'
  validates :author_id, uniqueness: { scope: :article_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, expect: %i[edit update new create]
  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success] = 'Your Article is created!'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'Something went wrong!'
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = 'Your Article is  updated1'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:success] = 'Your Article is  deleted '
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :image, :category_list)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, expect: %i[edit update new create]
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Your Category is created'
      redirect_to category_path(@category)
    else
      flash[:alert] = 'Something went wrong!'
      render 'new'
    end
  end

  def new
    @category = Category.new
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(article_params)
      flash[:success] = 'Your Category is  updated '
      redirect_to category_path(@category)
    else
      flash[:alert] = 'Something went wrong!'
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = 'Your category is deleted '
    else
      flash[:alert] = 'Something went wrong!'
    end
    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all.includes(:author).by_most_recent
    @categories = Category.all.by_most_recent.limit(4)
    @array = []
    Article.all.each { |article| @array << article.votes }
    @votes_array = []
    @array.each { |vote| @votes_array << vote.count }
    @most_voted = @votes_array.max(1).first
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_votes
  def create
    @vote = current_user.votes.new(article_id: @article.id)
    if @vote.save
      flash[:success] = 'You just voted for this article'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to root_path
    end
  end

  def destroy
    vote = Vote.find_by(id: params[:id], author: current_user, article_id: @article.id)
    if vote
      vote.destroy
      flash[:success] = 'You just unvoted this article'
      redirect_to article_path(@article)
    else
      flash[:alert] = 'Something went wrong'
      redirect_to root_path
    end
  end

  private

  def set_votes
    @article = Article.find(params[:article_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def voting(article)
    vote = Vote.find_by(author: current_user, article: article)
    if vote
      link_to('👍', article_vote_path(id: vote.id, article_id: article.id), method: :delete)
    else
      link_to('👌', article_votes_path(article_id: article.id), method: :post)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_form.html.erb
<div class="w-75 mx-auto px-5 text-secondary">

<%= form_with(model: @article, local: true) do |f| %>
<div class="form-group">
 <%= f.label :title, "Title" %>
 <%= f.text_field :title, class:"form-control"%>
</div>
<div class="form-group">
 <%= f.label :content, "Content" %>
 <%= f.text_area :content, class:"form-control", rows: "4"%>
</div>
<div class="form-group">
 <%= f.label :category_list, "Category" %>
 <%= f.text_area :category_list, class:"form-control" %>
</div>
    
<div class="form-group">
 <%= f.file_field :image,style:"display:none;" %>
 <%= f.label :image, "Upload image",class:"btn btn-secondary  btn-lg active"%>

</div>
<%= f.submit "Publish", class:"btn btn-primary btn-lg btn-block  " %>

<%end%>
</div>

app/views/articles/_links.html.erb
            <%= link_to "Edit", edit_article_path(@article),class:"btn btn-dark btn-sm ml-5 " %>
             <%= link_to "Delete",article_path(@article), method: :delete, class:"btn btn-danger btn-sm " %>

app/views/articles/edit.html.erb
<h2 class="text-center font-weight-bold text-orange text-uppercase">Edit Article</h2>
<%= render "articles/form" %>

app/views/articles/new.html.erb
<h2 class="font-weight-bold text-center text-uppercase">New Article</h2>

<%= render "articles/form" %>

app/views/articles/show.html.erb
<div class= "container article-section">

    <div class="text-center h4 text-uppercase   ">
      <%= @article.title %> 
      <br>
    </div>
     <br>
    <div id="articles-<%= @article.id %>" class="image">
       <%= image_tag @article.image.url, class:"img-fluid rounded mx-auto d-block" %>
    </div>
    <br>
    
      <div class="w-75 m-auto"></div>
        <div class="row ml-5">
          <div class="col-6">
             <span class="d-inline-flex p-2 ml-5 ">
             <h4> <%= @article.votes.count%><h4><%=  voting(@article)  %>
            </span>
            <p class="timestamp text-secondary small">
                Created by <%= @article.author.name%>  <%= time_ago_in_words(@article.created_at) %> ago. 
           </p>
          </div>
          <div class="col-6 p-2  ">
           
          <%= render 'articles/links'%>
          
          </div>
        </div>
      </div>
    
     <div class="text-center m-auto col-8">
      <span class="content-article"><%= @article.content %></span>
         
    </div>
  
      <br>
      </div>

app/views/categories/_form.html.erb
<%= form_with(model: @category, local: true) do |f| %>
 <%= f.label :name, "Name" %>
 <%= f.text_field :name %>
<%= f.submit "Publish", class:"btn btn-primary" %>
<% end %>

app/views/categories/edit.html.erb
<%= render "categories/form" %>

app/views/categories/index.html.erb
<% @categories.each do |a|%>
<%= a.name%>
<%= link_to "Edit", edit_category_path(a) %>             
<%= link_to "Delete", category_path(a), method: :delete %>    
<%end%>

app/views/categories/new.html.erb
<%= render "categories/form" %>

app/views/categories/show.html.erb
<div class="container col-12 show-cate">
      <div class="row d-flex ">
            <% @category.articles.by_most_recent.each do |c| %>
         <div class="col-md-3 mb-5">
            
               <%= image_tag c.image.url, class:" img-fluid" %>
         </div>
    
        <div class="col-md-3">

          <%= link_to c.title, article_path(c), class:"h3 show-title"%>
          <hr>
          <p>  <%= c.content.first(80) %></p>
           <%= link_to "SEE MORE ", article_path(c), class:" card-link small"%>

        </div>
       <%end%>
      </div>

app/views/home/index.html.erb
<div class="row container-fluid h-100 m-0  big-section">
  <% @articles.each do |a| %>
    <div class="card col-lg-12 col-md-12 col-sm-12 col-xs-12  border-0">
     
        <%= image_tag a.image.url ,class:"img-fluid hv-100"%>
        <div class="card-img-overlay  text-white d-flex d-flex align-items-end mt-auto h-25 ">
          <%= link_to a.title, article_path(a),class:"text-orange w-50 h-50 ml-5 mt-2 p-3 "%>
        </div>
    </div>
  <%end%>
</div>
 
   


<div class="row container-fluid m-0 border-0">
      <div class="col d-flex">
          <% @categories.each do |c|%>
              <% @articles.each do |a| %>
                 <% if c.articles.last == a %>
                   <div class="card text-white w-100">
                     <%=  image_tag a.image.url, class: "img-fluid w-100 h-100" %>
                       <div class="card-img-overlay w-100">
                             
                                <span class="w-auto" ><%= link_to c.name, category_path(c), class:"text-uppercase"%></span>
                             
                      
                             <div class="d-flex align-items-end mt-4 h-75 small">
                                <%= link_to a.title, article_path(a),class:"text-white" %> 
                             </div>

                        </div>

                        </div>
                   <%end%>
               <%end%>
            <%end%>
       </div>
    </div>
  

app/views/layouts/_footer.html.erb
<footer class="footer p-0 m-0 container-fluid">
      <div class="row align-items-center m-0">
        <div class="col-sm mt-3">
          <p class="main-logo">
            <span class="primary">EVERYTHINGBLOG</span>
          </p>
        </div>

        <div class="col-sm mt-3">
          <p>
            <small class="policy">Privacy Policy <span class="text-light">|</span> Terms & Conditions</small>
            <small> &copy; 2020 EverythingBlog. All rights reserved.</small>
          </p>
        </div>

        <div class="col-sm social-links mt-3">
          <p class="text-center">
            Contact Us: &nbsp;
            <span class="col-sm-3">
              <a href="" target="_blank" class="icon">
                <i class="fab fa-twitter"></i>
              </a>           
            </span>

            <span class="col-sm-3">
              <a href="" target="_blank" class="icon">
                <i class="fab fa-facebook-f"></i>
              </a>           
            </span>

            <span class="col-sm-3">
              <a href="" target="_blank" class="icon">
                <i class="fab fa-instagram"></i>
              </a>           
            </span>
          </p>
        </div>
      </div>
    </footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg  bg-dark fixed-top  ">
    <div class="container">
      <a class="navbar-brand text-light">
      <%= link_to root_path, class:"navbar-item text-muted" do %>
          <h1 class="title h4">EverythingBlog<span class="text-warning"></span></h1>
        <% end  %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarResponsive">

        <div class="d-flex align-items-center text-uppercase ml-5">
        
        <ul class="navbar-nav d-flex ml-5 ">
          <% Category.all.limit(6).each do |c| %>
         <li>
            <%= link_to c.name, category_path(c), class:"navbar-link text-muted  p-2" %>
         </li>
         <%end%>
    </ul>
      
        
        </div>
         
        
        <ul class="navbar-nav ml-auto t text-uppercase align-items-center">
           <% if user_signed_in? %>
                <li>
                <%= link_to "Create new article",new_article_path, class: "navbar-link  p-3 text-muted" %>
                </li>
                <ul class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle m-32" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="text-muted p-2"><%= current_user.name%><span>
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                     <li class="dropdown-item navdrop-link">  
                        <%= link_to "Edit profile ", edit_user_registration_path, class:"navbar-item text-muted" %>
                         </li> 
                     <li class="dropdown-item navdrop-link">  
                        <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class:"navbar-link text-muted" %>
                     </li>          
                  </div>
                </ul>
    
            <% else %>
               <li>
              <%= link_to "LOG IN", new_user_session_path, class:"navbar-link  p-3 text-uppercase"%>  
               </li> 
              <li>
               <%= link_to "SIGN UP", new_user_registration_path, class:"navbar-link text-uppercase"%>         
            </li>
        </ul>
        <%end%>
      </div>
    </div>
  </nav>
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EverythingBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/nav"%>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <div class="Container">
    <%= yield %>
    </div>
  <%= render "layouts/footer"%>
</html>